Create pt.lua
qbcore-framework/qb-busjob pull request #22
Opened 2022-01-25 19:55 UTC by StOnEOP

2022-03-16 00:23 UTC, DanielCoelh0 requested changes
Is "Deixaste" not "Deixas-te". Otherwise everything looked ok

2022-03-16 10:12 UTC, StOnEOP commented
> Is "Deixaste" not "Deixas-te". Otherwise everything looked ok

True, it's fixed now, Thank you.

2022-03-16 10:15 UTC, DanielCoelh0 approved these changes
is good to merge

2022-03-17 23:59 UTC, MrKualaPT approved these changes

2022-04-07 01:14 UTC, merged