Blip shows only player with bus job
qbcore-framework/qb-busjob pull request #24
Opened 2022-02-15 15:03 UTC by Tomboru

So with my version the blips only get created for the player, when they have the bus job.
Also when they change the job, the blip gets removed.

I tested this Code, and its working without any problems and this code should fit for QB

2022-03-09 19:43 UTC, ItsANoBrainer requested changes
Just one change then this is good to go.

2022-03-09 19:43 UTC, ItsANoBrainer commented on client/main.lua
> +    end
Remove the job check here, as SetupClient already does it.

2022-04-07 01:15 UTC, GhzGarage commented
Has conflicts now, if you don't wanna fix let me know

2022-04-17 16:53 UTC, Tomboru commented
> Has conflicts now, if you don't wanna fix let me know

Gonna do it now

2022-06-08 15:59 UTC, tom-osborne commented
> > Has conflicts now, if you don't wanna fix let me know
> 
> Gonna do it now

Hi @Tomboru, this still has conflicts. Are you planning to fix them? 
I'd like to get this merged if possible.
Thanks

2022-06-10 09:49 UTC, closed without merging